---

  - name: Create env file on target
    template:
      src: templates/mysql-env-file
      dest: ~/mysql-env-file
    tags:
      - quay
      - quay-config
      - quay-worker
      - redis
      - database

  - name: Create /var/lib/mysql
    file:
      path: /var/lib/mysql
      state: directory
      mode: '0777'
    tags:
      - quay
      - quay-config
      - quay-worker
      - redis
      - database

  - name: Deploy mysql container
    docker_container:
      env_file: "~/mysql-env-file"
      detach: yes
      restart: yes
      name: "{{ MYSQL_CONTAINER_NAME }}"
      privileged: yes
      published_ports: 3306:3306
      volumes: /var/lib/mysql:/var/lib/mysql/data:Z
      image: "registry.access.redhat.com/rhscl/mysql-57-rhel7"
      restart_policy: "{{ CONTAINER_RESTART_POLICY }}"
    tags:
      - quay
      - quay-config
      - quay-worker
      - redis
      - database

