---
  - name: Install Docker and dependencies
    yum:
      name: "{{ docker_packages }}" 
      state: latest
    tags:
      - quay
      - quay-config
      - quay-worker
      - redis
      - database
      - docker

  - name: Start and enable docker
    systemd:
      name: docker
      state: started
      enabled: true
    tags:
      - quay
      - quay-config
      - quay-worker
      - redis
      - database
      - docker
