---

- name: Install podman and dependencies
  ansible.builtin.package:
    name:
      - podman
      - jq
      - git
      - make
      - golang
      - dnsmasq
    state: latest

- name: Check if default podman network is configured
  lineinfile:
    path: /etc/cni/net.d/87-podman-bridge.conflist
    regexp: 'dns.podman'
    state: absent
  check_mode: yes
  changed_when: false
  register: dns_config

- name: Configure podman with CNI DNS plugin
  block:
    - name: Clone podman CNI DNS plugin
      ansible.builtin.git:
        repo: 'https://github.com/containers/dnsname.git'
        dest: '/tmp/dnsname'

    - name: Build DNS plugin
      community.general.make:
        chdir: '/tmp/dnsname'
        target: all

    - name: Install DNS plugin
      community.general.make:
        chdir: '/tmp/dnsname'
        target: install
        params:
          PREFIX: '/usr'

    - name: Remove DNS plugin cloned repo
      file:
        path: '/tmp/dnsname'
        state: absent

    - name: Add dns plugin to default network
      command: >
         jq '.plugins += [{"type":"dnsname","domainName":"dns.podman","capabilities":{"aliases":true}}]' /etc/cni/net.d/87-podman-bridge.conflist
      register: cni_json

    - name: Replace default network conflist
      copy:
        content: "{{ cni_json.stdout }}"
        dest: /etc/cni/net.d/87-podman-bridge.conflist
  when: not dns_config.found
