---

- name: Install podman
  ansible.builtin.package:
    name: podman
    state: latest

- name: Install CNI DNS dependencies
  ansible.builtin.package:
    name:
      - jq
      - git
      - make
      - golang
      - dnsmasq

- name: Clone podman CNI DNS plugin
  ansible.builtin.git:
    repo: 'https://github.com/containers/dnsname.git'
    dest: '/tmp/dnsname'

- name: Build DNS plugin
  community.general.make:
    chdir: '/tmp/dnsname'
    target: all

- name: Install DNS plugin
  community.general.make:
    chdir: '/tmp/dnsname'
    target: install
    params:
      PREFIX: '/usr'

- name: Remove DNS plugin cloned repo
  file:
    path: '/tmp/dnsname'
    state: absent

- name: Add dns plugin to default network
  command: >
     jq '.plugins += [{"type":"dnsname","domainName":"dns.podman","capabilities":{"aliases":true}}]' /etc/cni/net.d/87-podman-bridge.conflist
  register: cni_json

- name: Replace default network conflist
  copy:
    content: "{{ cni_json.stdout }}"
    dest: /etc/cni/net.d/87-podman-bridge.conflist
