---
  
  - name: Start quay repository mirror worker
    docker_container:
       detach: true
       restart: true
      name: "mirroring-worker"
       privileged: false
      image: "{{ QUAY_IMAGE_VERSION }}"
      volumes:
        - "{{ QUAY_ROOT_DIR }}/config:/conf/stack:Z"
      command: "repomirror"
    tags:
      - quay-worker
